package settings

import "time"

// PostgresSettings configures PostgreSQL database connection pooling.
type PostgresSettings struct {
	MaxOpenConns    int           `key:"postgres_maxOpenConns" desc:"Maximum number of open database connections" default:"50" category:"Postgres" usage:"Adjust based on database server capacity" type:"int" longdesc:"### Purpose\nControls the upper limit of concurrent PostgreSQL database connections, affecting throughput and database server load.\n\n### How It Works\nThe connection pool maintains up to this many simultaneous connections. Each connection consumes memory on both client (~10KB) and server (~10MB with work_mem). Connections are reused across requests to avoid setup overhead.\n\n### Sizing Formula\n**max_connections_per_service** x **number_of_service_instances** should be less than **postgres_max_connections** minus reserved connections.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Higher | More concurrent queries | Database memory exhaustion |\n| Lower | Reduced resource usage | Operations queue, causing latency |\n\n### Recommendations\n| Environment | Suggested Value |\n|-------------|----------------|\n| Development | 10-25 |\n| Default | 50 |\n| Production | 100-500 |\n\nMonitor **InUse** vs **MaxOpenConns** in pool metrics to identify bottlenecks."`
	MaxIdleConns    int           `key:"postgres_maxIdleConns" desc:"Maximum number of idle connections in pool" default:"10" category:"Postgres" usage:"Should be less than maxOpenConns" type:"int" longdesc:"### Purpose\nControls how many pre-established connections remain ready for immediate use, avoiding connection setup latency.\n\n### How It Works\nIdle connections can be immediately used for new requests without TCP handshake and authentication overhead (~5-10ms savings). Connections exceeding this limit are closed. Idle connections are also closed after **ConnMaxIdleTime** to prevent staleness.\n\n### Values\nMust be less than or equal to **MaxOpenConns**.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Higher | Reduced connection churn, faster response | More memory consumed |\n| Lower | Resources freed faster | Connection overhead during traffic bursts |\n\n### Recommendations\n- Set to approximately **20-50%** of MaxOpenConns for typical workloads\n- Production environments with bursty traffic benefit from higher idle pools\n- Default of **10** balances memory usage and connection reuse"`
	ConnMaxLifetime time.Duration `key:"postgres_connMaxLifetime" desc:"Maximum time a connection can be reused" default:"5m" category:"Postgres" usage:"Helps prevent stale connections" type:"duration" longdesc:"### Purpose\nLimits how long a connection can be reused before being closed and replaced, ensuring connection freshness.\n\n### How It Works\nConnections are closed after this duration regardless of idle status. New requests get fresh connections. Does not forcibly close active connections - waits for operation completion. Works with database server **idle_in_transaction_session_timeout** settings.\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (1-3m) | Fresher connections, catches DNS changes | More connection churn overhead |\n| Longer (10-30m) | Reduced setup overhead | Risk of stale connections, memory leaks |\n\n### Recommendations\n| Scenario | Suggested Value |\n|----------|----------------|\n| Default | 5m |\n| Stale connection issues | 1-3m |\n| High-throughput | 10-30m |"`
	ConnMaxIdleTime time.Duration `key:"postgres_connMaxIdleTime" desc:"Maximum time a connection can remain idle" default:"1m" category:"Postgres" usage:"Reduces resource usage during low activity" type:"duration" longdesc:"### Purpose\nControls how long idle connections are kept before being closed, freeing resources during low-activity periods.\n\n### How It Works\nIdle connections exceeding this duration are closed and removed from the pool. Should be shorter than **ConnMaxLifetime** to ensure inactive connections are cleaned up first. Works with **MaxIdleConns** to manage pool size during varying traffic patterns.\n\n### Values\n- **> 0** - Close idle connections after this duration\n- **0** - Disable idle timeout (connections kept until lifetime expires)\n\n### Trade-offs\n| Setting | Benefit | Drawback |\n|---------|---------|----------|\n| Shorter (30s) | Aggressive resource cleanup | More reconnection overhead during bursts |\n| Longer (5m) | Better for bursty traffic | More memory consumed during idle periods |\n\n### Recommendations\n| Scenario | Suggested Value |\n|----------|----------------|\n| Default | 1m |\n| Resource-constrained | 30s |\n| Bursty traffic | 5m |\n| Disable timeout | 0 |"`
}
